name: C++ CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test with Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
